lsi: false
safe: true
source: LouiseBudzynski.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
title: Louise Budzynski
theme: jekyll-theme-minimal
description: Associate Professor at DI ENS, Ecole Normale Supérieure
